### ISSUE TITLE
Im just having trouble 

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/registration-form#1]
Im just kind of stuck on this one, I also have put the border and paddings but im not sure what it should go on. also markbot keeps saying this(picture) but I have everything that I need. 
<img width="503" alt="Screen Shot 2020-04-01 at 10 18 57 AM" src="https://user-images.githubusercontent.com/55094132/78147974-3f5c6d80-7402-11ea-9e6a-cb377760b67c.png">
-nikki 
@muxlowc
@ mackenzierose

**Comment by muxlowc** [comment]
@NikCasar 

1) So for all of your inputs/selects you need to add a name="". for example:
```
<label for="age">Age</label>
          <input type="number" id="age" name="age" required>
....
```
or
`<select id="fit" name="fitness">`

2) For the grid/units.. you currently have direct children of your grid that aren't units. Rather than putting your h1/p outside of your form, you can move those down into your `<form> ` and then add in a <div class="grid"> with units inside...This is part of the solution to get you started :) :

```
<body>
<form class="gutter pad-t-2 pad-b-2 max-length" method="POST" action="https://formspree.io/bradlet@algonquincollege.com">
    <h1 class="normal">Want to go to Mars?</h1>
    <p class="mega">We’re looking for super-awesome human beings who want to make the long trek to Mars for the adventure of a lifetime.</p>

    <fieldset class="push-0">
      <legend class="push italic giga">Personal details</legend>

      <div class="grid">
        
        <div class="space-right unit xs-1 s-1 m-1 l-1-2 push">
          <label for="name">Name</label>
          <input id="name" name="name" required>
        </div>
```
(notice too that Thomas didn't use a section for this one)
